cake-contrib/Cake.Svn

src/Cake.Svn.Tests/Cake.Svn.Tests.csproj, src/Cake.Svn.Tests/packages.config, src/Cake.Svn/Cake.Svn.csproj, src/Cake.Svn/packages.config
Build against Cake 0.22.0 and target .NET Framework 4.6
Fixes #13
=> (GH-13) Build against Cake 0.22.0 and target .NET Framework 4.6

src/Cake.Svn.Tests/Cake.Svn.Tests.csproj, src/Cake.Svn/Cake.Svn.csproj, src/Cake.Svn/Export/SvnExportResult.cs, src/Cake.Svn/Export/SvnExportSettings.cs, src/Cake.Svn/Export/SvnExporter.cs, src/Cake.Svn/ISvnClient.cs, src/Cake.Svn/SvnAliases.Export.cs, src/Cake.Svn/SvnAliases.cs, src/Cake.Svn/SvnCredentials.cs, src/Cake.Svn/SvnDepth.cs, src/Cake.Svn/SvnLineStyle.cs, src/Cake.Svn/SvnRemoteSettings.cs, src/Cake.Svn/SvnSettings.cs, src/Cake.Svn/SvnTool.cs
Enable XML documentation and add XML comments for existing functionality.
Fixes #15
=> (GH-15) Add XML comments for existing functionality

src/Cake.Svn.Tests/Fixtures/Export/SvnExporterFixture.cs, src/Cake.Svn.Tests/Unit/Export/SvnExportSettingsTests.cs, src/Cake.Svn.Tests/Unit/Export/SvnExporterTests.cs, src/Cake.Svn/Export/SvnExportResult.cs, src/Cake.Svn/Export/SvnExportSettings.cs, src/Cake.Svn/Export/SvnExporter.cs, src/Cake.Svn/ISvnClient.cs, src/Cake.Svn/Internal/Extensions/SvnDepthExtensions.cs, src/Cake.Svn/Internal/Extensions/SvnLineStyleExtensions.cs, src/Cake.Svn/Internal/SharpSvnClient.cs, src/Cake.Svn/SvnAliases.Export.cs, src/Cake.Svn/SvnCredentials.cs, src/Cake.Svn/SvnDepth.cs, src/Cake.Svn/SvnLineStyle.cs, src/Cake.Svn/SvnRemoteSettings.cs, src/Cake.Svn/SvnTool.cs
Cleanup not required using statements
=> Remove not required using statements

src/Cake.Svn/Cake.Svn.csproj, src/Cake.Svn/packages.config
Update SharpSVN to latest 1.9 version
=> (GH-20) Update SharpSVN to 1.9

src/Cake.Svn.Tests/Cake.Svn.Tests.csproj, src/Cake.Svn.Tests/packages.config
Update XUnit to 2.3.0 and add Visual Studio runner
Fixes #28
=> (GH-28) Update XUnit to 2.3.0 and add Visual Studio runner

src/Cake.Svn/SvnAliases.Export.cs
Add examples for SvnExport aliases to XML documentation
Fixes #23
=> (GH-23) Add examples to XML documentation

src/Cake.Svn.Tests/Cake.Svn.Tests.csproj, src/Cake.Svn.Tests/app.config, src/Cake.Svn.Tests/packages.config
Update NSubstitue to latest version
=> (GH-31) Update NSubstitue to 3.0.1

CONTRIBUTING.md
=> Add contributing information

src/Cake.Svn.Tests/Cake.Svn.Tests.csproj, src/Cake.Svn.Tests/Fixtures/Add/SvnAdderFixture.cs, src/Cake.Svn.Tests/Unit/Add/SvnAddSettingsTests.cs, src/Cake.Svn.Tests/Unit/Add/SvnAdderTests.cs, src/Cake.Svn/Add/SvnAddSettings.cs, src/Cake.Svn/Add/SvnAddSettingsExtensions.cs, src/Cake.Svn/Add/SvnAdder.cs, src/Cake.Svn/Cake.Svn.csproj, src/Cake.Svn/ISvnClient.cs, src/Cake.Svn/Internal/SharpSvnClient.cs, src/Cake.Svn/SvnAliases.Add.cs
=> (GH-26) Add feature to add files/directories to SVN.

src/Cake.Svn.Tests/Cake.Svn.Tests.csproj, src/Cake.Svn.Tests/Fixtures/Delete/SvnDeleterFixture.cs, src/Cake.Svn.Tests/Unit/Delete/SvnDeleteSettingsTests..cs, src/Cake.Svn.Tests/Unit/Delete/SvnDeleterTests.cs, src/Cake.Svn/Cake.Svn.csproj, src/Cake.Svn/Delete/SvnDeleteSettings.cs, src/Cake.Svn/Delete/SvnDeleteSettingsExtensions.cs, src/Cake.Svn/Delete/SvnDeleter.cs, src/Cake.Svn/ISvnClient.cs, src/Cake.Svn/Internal/SharpSvnClient.cs, src/Cake.Svn/SvnAliases.Delete.cs
=> (GH-27) Add feature to delete files/directories from SVN.

README.md
Add license, code coverage badge and contribution information to the README
=> Add license, code coverage badge and contrib info

src/Cake.Svn/Cake.Svn.csproj, src/Cake.Svn/SvnAliases.Add.cs, src/Cake.Svn/SvnAliases.Delete.cs
(GH-26) Corrections in example
(GH-27) Corrections in example, add reference to SvnAliases.Add.cs again (lost due rebase)
=> (GH-26) and (GH-27) corrections

src/Cake.Svn.Tests/Cake.Svn.Tests.csproj, src/Cake.Svn.Tests/Fixtures/Info/SvnInfoFixture.cs, src/Cake.Svn.Tests/Unit/Info/SvnInfoResultTests.cs, src/Cake.Svn.Tests/Unit/Info/SvnInfoSettingsTests.cs, src/Cake.Svn.Tests/Unit/Info/SvnInfoTests.cs, src/Cake.Svn/Cake.Svn.csproj, src/Cake.Svn/ISvnClient.cs, src/Cake.Svn/Info/SvnInfo.cs, src/Cake.Svn/Info/SvnInfoResult.cs, src/Cake.Svn/Info/SvnInfoSettings.cs, src/Cake.Svn/Internal/Extensions/SvnDepthExtensions.cs, src/Cake.Svn/Internal/Extensions/SvnInfoSettingsExtensions.cs, src/Cake.Svn/Internal/Extensions/SvnNodeKindExtensions.cs, src/Cake.Svn/Internal/SharpSvnClient.cs, src/Cake.Svn/SvnAliases.Info.cs, src/Cake.Svn/SvnDepth.cs, src/Cake.Svn/SvnKind.cs
=> (GH-8) Add feature to get information about to SVN.

README.md
Fixed some typos in the readme.md.
=> Readme typos fixed.

src/Cake.Svn/SvnSettings.cs
=> (GH-41) Added properties ThrowOnCancel, ThrowOnError and ThrowOnWarning

src/Cake.Svn.Tests/Unit/Add/SvnAddSettingsTests.cs, src/Cake.Svn.Tests/Unit/Delete/SvnDeleteSettingsTests..cs, src/Cake.Svn.Tests/Unit/Export/SvnExportSettingsTests.cs, src/Cake.Svn.Tests/Unit/Info/SvnInfoSettingsTests.cs, src/Cake.Svn/Add/SvnAddSettingsExtensions.cs, src/Cake.Svn/Cake.Svn.csproj, src/Cake.Svn/Delete/SvnDeleteSettingsExtensions.cs, src/Cake.Svn/Export/SvnExportSettingsExtensions.cs, src/Cake.Svn/Info/SvnInfoSettingsExtensions.cs, src/Cake.Svn/SvnClientArgsExtensions.cs
=> (GH-42) Mappings and tests for SvnSettings

src/Cake.Svn.Tests/Unit/Info/SvnInfoResultTests.cs, src/Cake.Svn.Tests/Unit/Info/SvnInfoSettingsTests.cs, src/Cake.Svn/Info/SvnInfoResult.cs, src/Cake.Svn/Info/SvnInfoSettings.cs, src/Cake.Svn/Info/SvnInfoSettingsExtensions.cs, src/Cake.Svn/Internal/SharpSvnClient.cs
=> (GH-50) change svn info settings default value of revision and depth

setup.cake, tools/packages.config
Update to Cake 0.23.0 for compatibility with latest Cake.Recipe
Fixes #52
=> (GH-52) Build with Cake 0.23.0

docs/input/docs/usage/examples.md, docs/input/docs/usage/index.cshtml
Add usage instructions to documentation
Fixes #24
=> (GH-24) Add usage instructions to documentation

src/Cake.Svn.Tests/Cake.Svn.Tests.csproj, src/Cake.Svn.Tests/Fixtures/Checkout/SvnCheckouterFixture.cs, src/Cake.Svn.Tests/Unit/Checkout/SvnCheckoutSettingsTests.cs, src/Cake.Svn.Tests/Unit/Checkout/SvnCheckouterTests.cs, src/Cake.Svn.Tests/Unit/Info/SvnInfoSettingsTests.cs, src/Cake.Svn/Cake.Svn.csproj, src/Cake.Svn/Checkout/SvnCheckoutResult.cs, src/Cake.Svn/Checkout/SvnCheckoutSettings.cs, src/Cake.Svn/Checkout/SvnCheckoutSettingsExtensions.cs, src/Cake.Svn/Checkout/SvnCheckouter.cs, src/Cake.Svn/ISvnClient.cs, src/Cake.Svn/Internal/SharpSvnClient.cs, src/Cake.Svn/SvnAliases.Checkout.cs
Adding a checkout alias for issue #11 
Fixes #11
=> (GH-11) Add Checkout alias

src/Cake.Svn.Tests/Cake.Svn.Tests.csproj, src/Cake.Svn.Tests/packages.config, src/Cake.Svn/Cake.Svn.csproj, src/Cake.Svn/packages.config
Build against Cake 0.26.0 to support Cake 0.26.0 and higher
=> (GH-57) Build against Cake 0.26.0

src/Cake.Svn.Tests/Cake.Svn.Tests.csproj, src/Cake.Svn.Tests/app.config, src/Cake.Svn.Tests/packages.config
Update XUnit, NSubstitute and .NET packages for the test assembly
=> Update XUnit, NSubstitute and .NET packages

src/Cake.Svn.Tests/Cake.Svn.Tests.csproj, src/Cake.Svn.Tests/packages.config, src/Cake.Svn/Cake.Svn.csproj, src/Cake.Svn/packages.config
Build against Cake 0.28.0
Part of #17
=> (GH-17) Build against Cake 0.28.0

nuspec/nuget/Cake.Svn.nuspec
Use jsDelivr for icon since RawGit is shutting down
=> Use jsDelivr for icon

src/Cake.Svn.Tests/Unit/Info/SvnInfoResultTests.cs, src/Cake.Svn/Info/SvnInfoResult.cs, src/Cake.Svn/Internal/SharpSvnClient.cs
Now in the develop branch.
Implemented the support for the property LastChangedRevision and a corresponding test.
Fixes #69
=> (GH-69) Add LastChangedRevision property to SvnInfo

src/Cake.Svn.Tests/Cake.Svn.Tests.csproj, src/Cake.Svn.Tests/Fixtures/Update/SvnUpdaterFixture.cs, src/Cake.Svn.Tests/Unit/Update/SvnUpdateSettingsTests.cs, src/Cake.Svn.Tests/Unit/Update/SvnUpdaterTests.cs, src/Cake.Svn/Cake.Svn.csproj, src/Cake.Svn/ISvnClient.cs, src/Cake.Svn/Internal/SharpSvnClient.cs, src/Cake.Svn/SvnAliases.Update.cs, src/Cake.Svn/SvnTool.cs, src/Cake.Svn/Update/SvnUpdateResult.cs, src/Cake.Svn/Update/SvnUpdateSettings.cs, src/Cake.Svn/Update/SvnUpdateSettingsExtensions.cs, src/Cake.Svn/Update/SvnUpdater.cs
Changes to implement SvnUpdate feature for issue #9 
(This is my first ever pull request so please be gentle)
Fixes #9
=> (GH-9) Add svn update
